version: '3.1'

services:
    wordpress:
        image: wordpress
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: marmishmish
            WORDPRESS_DB_USER: marmishuse
            WORDPRESS_DB_PASSWORD: marmishpass
        ports:
            - '2345:80'
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - db

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: marmishmish
            MYSQL_USER: marmishuse
            MYSQL_PASSWORD: marmishpass
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./data.sql:/docker-entrypoint-initdb.d/dump.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
