name: CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: ls
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./wordpress/
          remote: /var/www/html/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
