name: CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Test
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          exit
        
      - name: Deploy with rsync
        run: sudo rsync -avz ./wordpress/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
