name: CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: parent working directory
        run: pwd
      - name: LS
        run:  ls
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/marmishlag/marmishlag/wordpress
          remote: /var/www/html
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
